# Generated by Django 5.0.1 on 2024-02-04 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_mailing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь-владелец'),
        ),
        migrations.AddField(
            model_name='mail',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь-владелец'),
        ),
        migrations.AddField(
            model_name='mailingsrv',
            name='mail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_mailing.mail', verbose_name='письмо'),
        ),
        migrations.AddField(
            model_name='mailingsrv',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь-владелец'),
        ),
        migrations.AddField(
            model_name='mailingsrv',
            name='recipients',
            field=models.ManyToManyField(to='app_mailing.client', verbose_name='получатели рассылки'),
        ),
        migrations.AddField(
            model_name='mail',
            name='mailings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mails', to='app_mailing.mailingsrv', verbose_name='рассылки'),
        ),
        migrations.AddField(
            model_name='log',
            name='mailing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_mailing.mailingsrv', verbose_name='рассылка'),
        ),
    ]
